In [1]:
using Plots
using LinearAlgebra
using SparseArrays
using LightGraphs
using GraphPlot
using DisplayAs
using DelimitedFiles
using FFTW
using Random
using LightLattices
using StaticArrays
using Base.Threads
using Dates

include("WormPyrochlore.jl")
include("wormsanitychecks.jl")
include("W3W4functions.jl")

L2vdwRealSpace (generic function with 1 method)

In [2]:
Nlist=[8,8,8];

In [3]:
config0=zeros(4,Nlist[1],Nlist[2],Nlist[3]);
for k in 1:Nlist[3]
    for j in 1:Nlist[2]
        for i in 1:Nlist[1]
            config0[1,i,j,k]=1
            config0[2,i,j,k]=1
            config0[3,i,j,k]=-1
            config0[4,i,j,k]=-1
        end
    end
end

In [4]:
configpipi0=zeros(4,Nlist[1],Nlist[2],Nlist[3]);
for k in 1:Nlist[3]
    for j in 1:Nlist[2]
        for i in 1:Nlist[1]
            configpipi0[1,i,j,k]=1*(1-2*mod(i+j-2,2))
            configpipi0[2,i,j,k]=1*(1-2*mod(i+j-2,2))
            configpipi0[3,i,j,k]=-1*(1-2*mod(i+j-2,2))
            configpipi0[4,i,j,k]=-1*(1-2*mod(i+j-2,2))
        end
    end
end

In [5]:
configpi0pi=zeros(4,Nlist[1],Nlist[2],Nlist[3]);
for k in 1:Nlist[3]
    for j in 1:Nlist[2]
        for i in 1:Nlist[1]
            configpi0pi[1,i,j,k]=1*(1-2*mod(i+k-2,2))
            configpi0pi[2,i,j,k]=1*(1-2*mod(i+k-2,2))
            configpi0pi[3,i,j,k]=-1*(1-2*mod(i+k-2,2))
            configpi0pi[4,i,j,k]=-1*(1-2*mod(i+k-2,2))
        end
    end
end

In [6]:
loopbag=findshortflippableloop(config0,Nlist);

In [7]:
length(loopbag[1])

33

In [8]:
loopbag[1]

33-element Array{Array{Any,1},1}:
 [[1, 8, 7], 1]
 [[8, 8, 7], -1]
 [[8, 8, 8], 1]
 [[8, 8, 8], -1]
 [[8, 1, 8], 1]
 [[8, 1, 8], -1]
 [[8, 1, 1], 1]
 [[8, 1, 1], -1]
 [[8, 1, 2], 1]
 [[8, 1, 2], -1]
 [[8, 2, 2], 1]
 [[8, 2, 2], -1]
 [[8, 3, 2], 1]
 ⋮
 [[5, 4, 5], -1]
 [[5, 5, 5], 1]
 [[4, 5, 5], -1]
 [[4, 6, 5], 1]
 [[4, 6, 5], -1]
 [[4, 7, 5], 1]
 [[3, 7, 5], -1]
 [[3, 8, 5], 1]
 [[2, 8, 5], -1]
 [[2, 8, 6], 1]
 [[1, 8, 6], -1]
 [[1, 8, 7], 1]

In [9]:
loopbag[2]

32-element Array{Int64,1}:
 1
 3
 0
 2
 0
 3
 0
 3
 0
 2
 0
 2
 1
 ⋮
 0
 2
 1
 2
 0
 2
 1
 2
 1
 3
 1
 3

In [10]:
loopbag[3]

32-element Array{Array{Int64,1},1}:
 [2, 1, 8, 7]
 [4, 8, 8, 8]
 [1, 8, 8, 8]
 [3, 8, 1, 8]
 [1, 8, 1, 8]
 [4, 8, 1, 1]
 [1, 8, 1, 1]
 [4, 8, 1, 2]
 [1, 8, 1, 2]
 [3, 8, 2, 2]
 [1, 8, 2, 2]
 [3, 8, 3, 2]
 [2, 8, 3, 2]
 ⋮
 [1, 5, 4, 5]
 [3, 5, 5, 5]
 [2, 5, 5, 5]
 [3, 4, 6, 5]
 [1, 4, 6, 5]
 [3, 4, 7, 5]
 [2, 4, 7, 5]
 [3, 3, 8, 5]
 [2, 3, 8, 5]
 [4, 2, 8, 6]
 [2, 2, 8, 6]
 [4, 1, 8, 7]

In [11]:
config0[3, 1, 2, 2]

-1.0

In [12]:
winding(loopbag[2],1,1)

3-element Array{Int64,1}:
 -8
  8
  8

In [14]:
loopbag[3]

32-element Array{Array{Int64,1},1}:
 [2, 1, 8, 7]
 [4, 8, 8, 8]
 [1, 8, 8, 8]
 [3, 8, 1, 8]
 [1, 8, 1, 8]
 [4, 8, 1, 1]
 [1, 8, 1, 1]
 [4, 8, 1, 2]
 [1, 8, 1, 2]
 [3, 8, 2, 2]
 [1, 8, 2, 2]
 [3, 8, 3, 2]
 [2, 8, 3, 2]
 ⋮
 [1, 5, 4, 5]
 [3, 5, 5, 5]
 [2, 5, 5, 5]
 [3, 4, 6, 5]
 [1, 4, 6, 5]
 [3, 4, 7, 5]
 [2, 4, 7, 5]
 [3, 3, 8, 5]
 [2, 3, 8, 5]
 [4, 2, 8, 6]
 [2, 2, 8, 6]
 [4, 1, 8, 7]

In [15]:
confignew=newloopflip_config(config0,loopbag[3],Nlist);

In [16]:
electricflux(config0,1,2,Nlist)

32.0

In [17]:
electricflux(confignew,2,2,Nlist)

-31.0

In [18]:
loopbag=findLongflippableloop(configpipi0,Nlist);

In [19]:
loopbag[1]

9-element Array{Array{Any,1},1}:
 [[1, 8, 3], 1]
 [[1, 8, 3], -1]
 [[2, 8, 3], 1]
 [[2, 8, 2], -1]
 [[2, 8, 2], 1]
 [[2, 7, 2], -1]
 [[2, 7, 3], 1]
 [[1, 7, 3], -1]
 [[1, 8, 3], 1]

In [36]:
loopbag[3]

4-element Array{Array{Int64,1},1}:
 [1, 1, 1, 2]
 [4, 1, 1, 1]
 [1, 1, 1, 1]
 [4, 1, 1, 2]

In [20]:
confignew[1, 2, 2, 2]

1.0

In [21]:
winding(loopbag[2],1,1)

3-element Array{Int64,1}:
 0
 0
 0

In [22]:
confignew2=newloopflip_config(confignew,loopbag[3],Nlist);

In [23]:
electricflux(confignew2,3,2,Nlist)

-31.0

In [24]:
icerulecost(confignew,Nlist)

0.0

In [25]:
countflippablehex(configpipi0,Nlist)

LoadError: MethodError: no method matching rem(::Array{Int64,1}, ::Int64)
Closest candidates are:
  rem(::Any, ::Any, ::RoundingMode{:ToZero}) at div.jl:67
  rem(::Any, ::Any, ::RoundingMode{:Down}) at div.jl:68
  rem(::Any, ::Any, ::RoundingMode{:Up}) at div.jl:69
  ...

In [ ]:
countflippablehex(configpipi0,Nlist)

In [122]:
((loopbag[1])[1])[2]

-1

In [25]:
electricflux(configpipi0,3,1,Nlist)

0.0

In [80]:
res=enumerateconfigs(configpipi0,Nlist);

2th added, icerulecost=0.0, nflip=8
3th added, icerulecost=0.0, nflip=8
4th added, icerulecost=0.0, nflip=8
5th added, icerulecost=0.0, nflip=8
6th added, icerulecost=0.0, nflip=8
7th added, icerulecost=0.0, nflip=8
8th added, icerulecost=0.0, nflip=8
9th added, icerulecost=0.0, nflip=8
10th added, icerulecost=0.0, nflip=8
11th added, icerulecost=0.0, nflip=8
12th added, icerulecost=0.0, nflip=8
13th added, icerulecost=0.0, nflip=8
14th added, icerulecost=0.0, nflip=8
15th added, icerulecost=0.0, nflip=8
16th added, icerulecost=0.0, nflip=8
17th added, icerulecost=0.0, nflip=8
18th added, icerulecost=0.0, nflip=8
19th added, icerulecost=0.0, nflip=8
20th added, icerulecost=0.0, nflip=8
21th added, icerulecost=0.0, nflip=8
22th added, icerulecost=0.0, nflip=8
23th added, icerulecost=0.0, nflip=8
24th added, icerulecost=0.0, nflip=8
25th added, icerulecost=0.0, nflip=8
26th added, icerulecost=0.0, nflip=8
27th added, icerulecost=0.0, nflip=8
28th added, icerulecost=0.0, nflip=8
29th adde

259th added, icerulecost=0.0, nflip=8
260th added, icerulecost=0.0, nflip=8
261th added, icerulecost=0.0, nflip=8
262th added, icerulecost=0.0, nflip=8
263th added, icerulecost=0.0, nflip=8
264th added, icerulecost=0.0, nflip=8
265th added, icerulecost=0.0, nflip=8
266th added, icerulecost=0.0, nflip=8
267th added, icerulecost=0.0, nflip=8
268th added, icerulecost=0.0, nflip=8
269th added, icerulecost=0.0, nflip=8
270th added, icerulecost=0.0, nflip=8
271th added, icerulecost=0.0, nflip=8
272th added, icerulecost=0.0, nflip=8
273th added, icerulecost=0.0, nflip=8
274th added, icerulecost=0.0, nflip=8
275th added, icerulecost=0.0, nflip=8
276th added, icerulecost=0.0, nflip=8
277th added, icerulecost=0.0, nflip=8
278th added, icerulecost=0.0, nflip=8
279th added, icerulecost=0.0, nflip=8
280th added, icerulecost=0.0, nflip=8
281th added, icerulecost=0.0, nflip=8
282th added, icerulecost=0.0, nflip=8
283th added, icerulecost=0.0, nflip=8
284th added, icerulecost=0.0, nflip=8
285th added,

In [76]:
(sum(res[2])/384)/32

0.25

In [81]:
filename="4X2X2X2config.txt"
open(filename, "w") do io
    writedlm(filename,res[3])
end

In [19]:
configmadeup=initializebycopying([4,4,4]);

Oh oh 2000th repeat
Total 396


In [83]:
CountFlippableHex(configmadeup,[8,8,8])

512

In [72]:
count1=0
for i in 1:396
    if (res[2])[i]==0
        count1+=1
    end
end
println("$count1")

12


In [169]:
loopbag=findshortflippableloop(configpipi0,Nlist);

In [175]:
loopbag[1]

13-element Array{Array{Any,1},1}:
 [[1, 2, 1], 1]
 [[1, 2, 1], -1]
 [[2, 2, 1], 1]
 [[2, 2, 2], -1]
 [[2, 1, 2], 1]
 [[2, 1, 2], -1]
 [[2, 1, 1], 1]
 [[2, 1, 1], -1]
 [[1, 1, 1], 1]
 [[1, 1, 2], -1]
 [[1, 1, 2], 1]
 [[1, 1, 1], -1]
 [[1, 2, 1], 1]

In [171]:
loopbag[2]

12-element Array{Int64,1}:
 0
 1
 3
 2
 0
 3
 0
 1
 3
 0
 3
 2

In [172]:
loopbag[3]

12-element Array{Array{Int64,1},1}:
 [1, 1, 2, 1]
 [2, 2, 2, 1]
 [4, 2, 2, 1]
 [3, 2, 1, 2]
 [1, 2, 1, 2]
 [4, 2, 1, 1]
 [1, 2, 1, 1]
 [2, 1, 1, 1]
 [4, 1, 1, 1]
 [1, 1, 1, 2]
 [4, 1, 1, 2]
 [3, 1, 2, 1]

In [174]:
configpipi0[2, 2, 2, 1]

1.0

In [69]:
CountFlippableHex(configpipi0,Nlist)

0

In [85]:
RKnflipMC(configmadeup,[8,8,8],20)

0.25

In [5]:
interactionfourier1=vdwMatrixFourier(Nlist,1);

In [7]:
interactionfourier2=vdwMatrixFourierExtended(Nlist,1,10);

In [9]:
energycost_lr(config0,interactionfourier1,Nlist)

-2.049186193276744

In [10]:
energycost_lr(config0,interactionfourier2,Nlist)

-2.0746840026346707

In [12]:
Nmax=10
const1=0
for n3 in -Nmax:Nmax
    for n2 in -Nmax:Nmax
        for n1 in -Nmax:Nmax
            displacement=[0,0.5,0.5]+[(n2+n3)*Nlist[1],(n3+n1)*Nlist[2],(n1+n2)*Nlist[3]]
            distsquare=sum(abs2.(displacement))
            const1+=(2*distsquare)^(-6/2)
        end
    end
end
println("$const1")

1.0000008762888508


In [14]:
energycost_lr(configmadeup,interactionfourier2,Nlist)

12.877806405550672

In [15]:
energycost_lr(configmadeup,interactionfourier1,Nlist)

12.877773486529307

In [43]:
energycost_lr(configmadeup,interactionfourier3,Nlist)

12.877806405550672

In [9]:
intfourier2flat=reshape(interactionfourier2,8192);

In [38]:
typeof(interactionfourier2)

Array{Complex{Float64},5}

In [10]:
filename="4X8X8X8InteractionFourier.txt"
open(filename, "w") do io
    writedlm(filename,intfourier2flat)
end

In [32]:
interactionfourier3=loadfourierint();

LoadError: IOError: stat: unknown error (UNKNOWN) for file "4X8X8X8InteractionFourier.txt"

In [26]:
typeof(interactionfourier1)

Array{Complex{Float64},5}

In [27]:
typeof(interactionfourier2)

Array{Complex{Float64},5}

In [42]:
typeof(interactionfourier3)

Array{Complex{Float64},5}

In [37]:
interactionfourier4=reshape()

0.11292107782519101 + 0.0im

In [48]:
RKenergyMC(configmadeup,Nlist,200)

1: en=12.877806405550672
101: en_avg=13.325036160102036
201: en_avg=13.323269217933989


2-element Array{Any,1}:
 13.323269217933989
   [12.877806405550672, 13.532764447225132, 13.092241122179765]

In [10]:
vdwintmatrix=vdwMatrixRealExtended(Nlist,1,10);

In [21]:
vdwintmatrixflat=reshape(vdwintmatrix,8192);

In [22]:
filename="4X8X8X8vdWInteractionRealSpace.txt"
open(filename, "w") do io
    writedlm(filename,vdwintmatrixflat)
end

In [13]:
W2intfourier=W2vdwfourier(Nlist,vdwintmatrix);

Real space done


In [23]:
W2intfourierflat=reshape(W2intfourier,8192);

In [24]:
filename="4X8X8X8W2Fourier.txt"
open(filename, "w") do io
    writedlm(filename,W2intfourierflat)
end

In [16]:
energycost_lr(configmadeup,W2intfourier,Nlist)

-0.41817906471451216

In [17]:
energycost_lr(config0,W2intfourier,Nlist)

-0.008406862716373939

In [20]:
energycost_lr(configpipi0,W2intfourier,Nlist)

-0.7676729657108952

In [13]:
A=[1 -3;-4 1]

2×2 Array{Int64,2}:
  1  -3
 -4   1

In [22]:
enumerateneighbors([8,8,8])

1: Any[0, [0, 0, 0]], distance=0.0
2: Any[1, [0, 0, 0]], distance=1.0
3: Any[2, [0, 0, 0]], distance=1.0
4: Any[3, [0, 0, 0]], distance=1.0
5: Any[1, [1, 0, 0]], distance=1.0
6: Any[2, [0, 1, 0]], distance=1.0
7: Any[3, [0, 0, 1]], distance=1.0
8: Any[2, [1, 0, 0]], distance=1.7320508075688772
9: Any[3, [1, 0, 0]], distance=1.7320508075688772
10: Any[1, [0, 1, 0]], distance=1.7320508075688772
11: Any[3, [0, 1, 0]], distance=1.7320508075688772
12: Any[2, [7, 1, 0]], distance=1.7320508075688772
13: Any[1, [1, 7, 0]], distance=1.7320508075688772
14: Any[1, [0, 0, 1]], distance=1.7320508075688772
15: Any[2, [0, 0, 1]], distance=1.7320508075688772
16: Any[3, [7, 0, 1]], distance=1.7320508075688772
17: Any[3, [0, 7, 1]], distance=1.7320508075688772
18: Any[1, [1, 0, 7]], distance=1.7320508075688772
19: Any[2, [0, 1, 7]], distance=1.7320508075688772
20: Any[0, [1, 0, 0]], distance=2.0
21: Any[0, [7, 0, 0]], distance=2.0
22: Any[0, [0, 1, 0]], distance=2.0
23: Any[0, [7, 1, 0]], distance=2.0
2

216: Any[3, [1, 1, 6]], distance=4.123105625617661
217: Any[2, [2, 1, 6]], distance=4.123105625617661
218: Any[1, [0, 2, 6]], distance=4.123105625617661
219: Any[1, [1, 2, 6]], distance=4.123105625617661
220: Any[2, [7, 0, 7]], distance=4.123105625617661
221: Any[2, [7, 3, 7]], distance=4.123105625617661
222: Any[1, [0, 7, 7]], distance=4.123105625617661
223: Any[1, [3, 7, 7]], distance=4.123105625617661
224: Any[1, [2, 1, 0]], distance=4.358898943540674
225: Any[1, [6, 1, 0]], distance=4.358898943540674
226: Any[2, [1, 2, 0]], distance=4.358898943540674
227: Any[2, [7, 3, 0]], distance=4.358898943540674
228: Any[2, [1, 6, 0]], distance=4.358898943540674
229: Any[1, [3, 7, 0]], distance=4.358898943540674
230: Any[1, [7, 7, 0]], distance=4.358898943540674
231: Any[2, [7, 7, 0]], distance=4.358898943540674
232: Any[1, [2, 0, 1]], distance=4.358898943540674
233: Any[1, [6, 0, 1]], distance=4.358898943540674
234: Any[2, [0, 2, 1]], distance=4.358898943540674
235: Any[1, [7, 2, 1]], distanc

430: Any[0, [2, 1, 0]], distance=5.291502622129181
431: Any[0, [5, 1, 0]], distance=5.291502622129181
432: Any[0, [1, 2, 0]], distance=5.291502622129181
433: Any[0, [5, 2, 0]], distance=5.291502622129181
434: Any[0, [6, 3, 0]], distance=5.291502622129181
435: Any[0, [7, 3, 0]], distance=5.291502622129181
436: Any[0, [1, 5, 0]], distance=5.291502622129181
437: Any[0, [2, 5, 0]], distance=5.291502622129181
438: Any[0, [3, 6, 0]], distance=5.291502622129181
439: Any[0, [7, 6, 0]], distance=5.291502622129181
440: Any[0, [3, 7, 0]], distance=5.291502622129181
441: Any[0, [6, 7, 0]], distance=5.291502622129181
442: Any[0, [2, 0, 1]], distance=5.291502622129181
443: Any[0, [5, 0, 1]], distance=5.291502622129181
444: Any[0, [0, 2, 1]], distance=5.291502622129181
445: Any[0, [5, 2, 1]], distance=5.291502622129181
446: Any[0, [0, 5, 1]], distance=5.291502622129181
447: Any[0, [2, 5, 1]], distance=5.291502622129181
448: Any[0, [1, 0, 2]], distance=5.291502622129181
449: Any[0, [5, 0, 2]], distanc

636: Any[0, [6, 6, 3]], distance=6.0
637: Any[0, [0, 0, 5]], distance=6.0
638: Any[0, [3, 0, 5]], distance=6.0
639: Any[0, [2, 2, 5]], distance=6.0
640: Any[0, [7, 2, 5]], distance=6.0
641: Any[0, [0, 3, 5]], distance=6.0
642: Any[0, [2, 7, 5]], distance=6.0
643: Any[0, [3, 1, 6]], distance=6.0
644: Any[0, [6, 1, 6]], distance=6.0
645: Any[0, [1, 3, 6]], distance=6.0
646: Any[0, [6, 3, 6]], distance=6.0
647: Any[0, [1, 6, 6]], distance=6.0
648: Any[0, [3, 6, 6]], distance=6.0
649: Any[0, [2, 2, 7]], distance=6.0
650: Any[0, [5, 2, 7]], distance=6.0
651: Any[0, [2, 5, 7]], distance=6.0
652: Any[1, [2, 2, 0]], distance=6.082762530298219
653: Any[2, [2, 2, 0]], distance=6.082762530298219
654: Any[1, [5, 2, 0]], distance=6.082762530298219
655: Any[3, [5, 3, 0]], distance=6.082762530298219
656: Any[2, [6, 4, 0]], distance=6.082762530298219
657: Any[2, [2, 5, 0]], distance=6.082762530298219
658: Any[3, [3, 5, 0]], distance=6.082762530298219
659: Any[1, [4, 6, 0]], distance=6.082762530298219


844: Any[0, [7, 4, 6]], distance=6.6332495807108
845: Any[0, [4, 7, 6]], distance=6.6332495807108
846: Any[0, [7, 7, 6]], distance=6.6332495807108
847: Any[0, [6, 4, 7]], distance=6.6332495807108
848: Any[0, [7, 4, 7]], distance=6.6332495807108
849: Any[0, [4, 6, 7]], distance=6.6332495807108
850: Any[0, [7, 6, 7]], distance=6.6332495807108
851: Any[0, [4, 7, 7]], distance=6.6332495807108
852: Any[0, [6, 7, 7]], distance=6.6332495807108
853: Any[3, [3, 1, 0]], distance=6.708203932499369
854: Any[3, [1, 3, 0]], distance=6.708203932499369
855: Any[3, [6, 4, 0]], distance=6.708203932499369
856: Any[3, [4, 6, 0]], distance=6.708203932499369
857: Any[2, [3, 0, 1]], distance=6.708203932499369
858: Any[1, [0, 3, 1]], distance=6.708203932499369
859: Any[1, [5, 3, 1]], distance=6.708203932499369
860: Any[2, [3, 5, 1]], distance=6.708203932499369
861: Any[3, [7, 5, 1]], distance=6.708203932499369
862: Any[3, [5, 7, 1]], distance=6.708203932499369
863: Any[3, [5, 3, 2]], distance=6.70820393249936

1056: Any[0, [2, 3, 6]], distance=7.211102550927978
1057: Any[0, [5, 3, 6]], distance=7.211102550927978
1058: Any[0, [2, 5, 6]], distance=7.211102550927978
1059: Any[0, [3, 5, 6]], distance=7.211102550927978
1060: Any[0, [4, 0, 7]], distance=7.211102550927978
1061: Any[0, [5, 0, 7]], distance=7.211102550927978
1062: Any[0, [0, 4, 7]], distance=7.211102550927978
1063: Any[0, [5, 4, 7]], distance=7.211102550927978
1064: Any[0, [0, 5, 7]], distance=7.211102550927978
1065: Any[0, [4, 5, 7]], distance=7.211102550927978
1066: Any[3, [6, 4, 1]], distance=7.280109889280518
1067: Any[2, [7, 4, 1]], distance=7.280109889280518
1068: Any[2, [7, 5, 1]], distance=7.280109889280518
1069: Any[3, [4, 6, 1]], distance=7.280109889280518
1070: Any[1, [4, 7, 1]], distance=7.280109889280518
1071: Any[1, [5, 7, 1]], distance=7.280109889280518
1072: Any[2, [6, 1, 4]], distance=7.280109889280518
1073: Any[3, [7, 1, 4]], distance=7.280109889280518
1074: Any[1, [1, 6, 4]], distance=7.280109889280518
1075: Any[1,

1255: Any[3, [0, 3, 2]], distance=7.937253933193772
1256: Any[2, [5, 4, 2]], distance=7.937253933193772
1257: Any[1, [4, 5, 2]], distance=7.937253933193772
1258: Any[1, [6, 5, 2]], distance=7.937253933193772
1259: Any[2, [5, 6, 2]], distance=7.937253933193772
1260: Any[1, [2, 0, 3]], distance=7.937253933193772
1261: Any[2, [0, 2, 3]], distance=7.937253933193772
1262: Any[2, [6, 3, 3]], distance=7.937253933193772
1263: Any[3, [6, 3, 3]], distance=7.937253933193772
1264: Any[2, [6, 5, 3]], distance=7.937253933193772
1265: Any[1, [3, 6, 3]], distance=7.937253933193772
1266: Any[3, [3, 6, 3]], distance=7.937253933193772
1267: Any[1, [5, 6, 3]], distance=7.937253933193772
1268: Any[1, [5, 1, 4]], distance=7.937253933193772
1269: Any[1, [7, 1, 4]], distance=7.937253933193772
1270: Any[3, [5, 2, 4]], distance=7.937253933193772
1271: Any[2, [1, 5, 4]], distance=7.937253933193772
1272: Any[3, [2, 5, 4]], distance=7.937253933193772
1273: Any[2, [1, 7, 4]], distance=7.937253933193772
1274: Any[1,

1444: Any[0, [5, 5, 4]], distance=8.717797887081348
1445: Any[0, [6, 0, 5]], distance=8.717797887081348
1446: Any[0, [4, 2, 5]], distance=8.717797887081348
1447: Any[0, [5, 2, 5]], distance=8.717797887081348
1448: Any[0, [2, 4, 5]], distance=8.717797887081348
1449: Any[0, [5, 4, 5]], distance=8.717797887081348
1450: Any[0, [2, 5, 5]], distance=8.717797887081348
1451: Any[0, [4, 5, 5]], distance=8.717797887081348
1452: Any[0, [0, 6, 5]], distance=8.717797887081348
1453: Any[0, [5, 0, 6]], distance=8.717797887081348
1454: Any[0, [3, 3, 6]], distance=8.717797887081348
1455: Any[0, [0, 5, 6]], distance=8.717797887081348
1456: Any[1, [5, 4, 2]], distance=8.774964387392123
1457: Any[1, [6, 4, 2]], distance=8.774964387392123
1458: Any[2, [4, 5, 2]], distance=8.774964387392123
1459: Any[2, [4, 6, 2]], distance=8.774964387392123
1460: Any[1, [5, 2, 4]], distance=8.774964387392123
1461: Any[1, [6, 2, 4]], distance=8.774964387392123
1462: Any[2, [2, 5, 4]], distance=8.774964387392123
1463: Any[2,

1646: Any[1, [5, 3, 4]], distance=9.9498743710662
1647: Any[2, [3, 5, 4]], distance=9.9498743710662
1648: Any[3, [4, 3, 5]], distance=9.9498743710662
1649: Any[3, [3, 4, 5]], distance=9.9498743710662
1650: Any[0, [3, 2, 1]], distance=10.0
1651: Any[0, [2, 3, 1]], distance=10.0
1652: Any[0, [3, 1, 2]], distance=10.0
1653: Any[0, [1, 3, 2]], distance=10.0
1654: Any[0, [2, 1, 3]], distance=10.0
1655: Any[0, [1, 2, 3]], distance=10.0
1656: Any[0, [5, 4, 3]], distance=10.0
1657: Any[0, [4, 5, 3]], distance=10.0
1658: Any[0, [5, 3, 4]], distance=10.0
1659: Any[0, [3, 5, 4]], distance=10.0
1660: Any[0, [4, 3, 5]], distance=10.0
1661: Any[0, [3, 4, 5]], distance=10.0
1662: Any[0, [7, 6, 5]], distance=10.0
1663: Any[0, [6, 7, 5]], distance=10.0
1664: Any[0, [7, 5, 6]], distance=10.0
1665: Any[0, [5, 7, 6]], distance=10.0
1666: Any[0, [6, 5, 7]], distance=10.0
1667: Any[0, [5, 6, 7]], distance=10.0
1668: Any[3, [4, 2, 0]], distance=10.04987562112089
1669: Any[3, [2, 4, 0]], distance=10.049875621

1847: Any[3, [4, 4, 6]], distance=11.704699910719626
1848: Any[0, [4, 2, 1]], distance=11.832159566199232
1849: Any[0, [2, 4, 1]], distance=11.832159566199232
1850: Any[0, [4, 1, 2]], distance=11.832159566199232
1851: Any[0, [1, 4, 2]], distance=11.832159566199232
1852: Any[0, [2, 1, 4]], distance=11.832159566199232
1853: Any[0, [1, 2, 4]], distance=11.832159566199232
1854: Any[2, [7, 4, 4]], distance=11.958260743101398
1855: Any[3, [7, 4, 4]], distance=11.958260743101398
1856: Any[1, [4, 7, 4]], distance=11.958260743101398
1857: Any[3, [4, 7, 4]], distance=11.958260743101398
1858: Any[1, [4, 4, 7]], distance=11.958260743101398
1859: Any[2, [4, 4, 7]], distance=11.958260743101398
1860: Any[0, [6, 4, 4]], distance=12.0
1861: Any[0, [4, 6, 4]], distance=12.0
1862: Any[0, [4, 4, 6]], distance=12.0
1863: Any[0, [4, 3, 0]], distance=12.165525060596439
1864: Any[0, [3, 4, 0]], distance=12.165525060596439
1865: Any[0, [4, 0, 3]], distance=12.165525060596439
1866: Any[0, [0, 4, 3]], distance=1

2045: Any[1, [4, 4, 4]], distance=18.788294228055936
2046: Any[2, [4, 4, 4]], distance=18.788294228055936
2047: Any[3, [4, 4, 4]], distance=18.788294228055936
2048: Any[0, [4, 4, 4]], distance=19.595917942265423


In [24]:
configin=initializebycopying([4,4,4]);

Oh oh 2000th repeat
Total 396


In [8]:
size(configin)

(4, 2, 2, 2)

In [18]:
intfourier=loadfourierint("4X8X8X8InteractionFourier.txt");

In [9]:
W3W4vdwcalc(configin,[8,8,8],intfourier)

2-element Array{Complex{Float64},1}:
   0.0014555347136379182 + 0.0im
 -2.2685428299266784e-21 + 0.0im

In [14]:
W3W4vdwcalc(configin,[8,8,8],intfourier)

2-element Array{Float64,1}:
  0.0014555347136379184
 -6.533669950278153e-5

In [17]:
W3W4vdwcalc(configin,[8,8,8],intfourier)

2-element Array{Float64,1}:
  0.001455534713637976
 -6.533669950327007e-5

In [21]:
W3W4vdwcalc(configin,[8,8,8],intfourier)

2-element Array{Float64,1}:
  0.0037156893932813813
 -0.0001711490530696327

In [26]:
W3W4vdwcalc(configin,[8,8,8],intfourier)

2-element Array{Float64,1}:
  0.0019075656495666166
 -8.649917021606519e-5

In [3]:
RK_MC_with_W3W4([8,8,8],20,1)

Oh oh 2000th repeat
Total 396
1: HLRavg=13.007945090106455, W2avg=-0.5515598802653549, W3avg=0.0, W4avg=0.0
2: HLRavg=13.245958198737416, W2avg=-0.5614602970969169, W3avg=0.0, W4avg=0.0
3: HLRavg=13.401137492535057, W2avg=-0.5729849852428005, W3avg=0.0, W4avg=0.0
4: HLRavg=13.323799409462705, W2avg=-0.5680328698213497, W3avg=0.0, W4avg=0.0
5: HLRavg=13.280325918105472, W2avg=-0.5663227745085344, W3avg=0.0, W4avg=0.0
6: HLRavg=13.222356416025633, W2avg=-0.5630271483017654, W3avg=0.0, W4avg=0.0
7: HLRavg=13.168171785660444, W2avg=-0.5604615449480335, W3avg=0.0, W4avg=0.0
8: HLRavg=13.188983424523842, W2avg=-0.5621801088226438, W3avg=0.0, W4avg=0.0
9: HLRavg=13.236630668480222, W2avg=-0.563823232392866, W3avg=0.0, W4avg=0.0
10: HLRavg=13.234476536364483, W2avg=-0.5638839877248544, W3avg=0.0, W4avg=0.0
11: HLRavg=13.243360675072404, W2avg=-0.5652549345168019, W3avg=0.0, W4avg=0.0
12: HLRavg=13.266489339523332, W2avg=-0.5674814309643286, W3avg=0.0, W4avg=0.0
13: HLRavg=13.258044229123843, W

5-element Array{Float64,1}:
  0.1745849609375
 13.307312265679098
 -0.5716436889738495
  0.0
  0.0

In [5]:
RK_MC_with_W3W4([8,8,8],3,1)

Oh oh 2000th repeat
Total 395
1: HLRavg=13.425717520762314, W2avg=-0.5832847339252758, W3avg=0.00345591517170432, W4avg=-0.00011115964253681986
2: HLRavg=13.407052283999972, W2avg=-0.5781497279269112, W3avg=0.0034128323258048538, W4avg=-0.00011440060451601482
3: HLRavg=13.406603126666957, W2avg=-0.5746396958647128, W3avg=0.003392406862297063, W4avg=-0.00011471160141347864


5-element Array{Float64,1}:
  0.17887369791666666
 13.406603126666957
 -0.5746396958647128
  0.003392406862297063
 -0.00011471160141347864

In [3]:
neighbdata(5,0)

2-element Array{Any,1}:
  [0, 1, 0]
 2

In [4]:
2*[1,3.3]

2-element Array{Float64,1}:
 2.0
 6.6

In [ ]:
M2vdwcalc(configin,[8,8,8],intfourier)

In [3]:
typeof(3.4)

Float64

In [4]:
vdwintmatrix=reshape(readdlm("4X8X8X8vdWInteractionRealSpace.txt",'\t',Float64,'\n',comments=true),(4,4,8,8,8));

In [5]:
L2vdWmat=L2vdwRealSpace([8,8,8],vdwintmatrix);

Real space done


In [7]:
L2vdWmatFourier=fft(L2vdWmat,[3,4,5]);

In [8]:
filename="4X8X8X8L2vdWFourier.txt"
open(filename, "w") do io
    writedlm(filename,reshape(L2vdWmatFourier,8192))
end

In [11]:
energycost_lr(configin, L2vdWmatFourier, [8,8,8]) 

-0.6616111789308948

In [17]:
energycost_lr(configpi0pi, L2vdWmatFourier, [8,8,8]) 

-1.535345931421657

In [83]:
configin=initializebycopying([8,8,8]);

Oh oh 2000th repeat
Total 395


In [ ]:
M2vdwcalc(configin,[8,8,8],intfourier)

In [44]:
vdwintmatrix=vdwMatrixRealExtended([4,4,4],1,10);

In [82]:
vdwintfourier=loadfourierint("4X8X8X8InteractionFourier.txt");

In [45]:
vdwintfourier=fft(vdwintmatrix,[3,4,5]);

In [48]:
energycost_lr(configin,vdwintfourier,[4,4,4])/64

0.02515050057330676

In [49]:
@time M2vdwcalc(configin, [4,4,4], vdwintfourier)

104.661871 seconds (1.96 G allocations: 89.250 GiB, 14.64% gc time)


1.0658591729708868 + 2.1026316706164913e-18im

In [53]:
@time M2vdwcalc(configin, [4,4,4], vdwintfourier)

 23.913967 seconds (251.90 M allocations: 26.263 GiB, 12.53% gc time)


0.9715932350277648 - 1.5477933760515556e-19im

In [54]:
@time M2vdwcalc(configin, [4,4,4], vdwintfourier)

 24.260577 seconds (251.66 M allocations: 26.250 GiB, 12.54% gc time)


0.9715932350277648 - 1.5477933760515556e-19im

In [56]:
@time M2vdwcalc(configin, [4,4,4], vdwintfourier)

 23.992207 seconds (251.94 M allocations: 26.265 GiB, 12.57% gc time)


0.9715932350277648 - 1.5477933760515556e-19im

In [58]:
@time M2vdwcalc(configin, [4,4,4], vdwintfourier)

 23.296193 seconds (251.92 M allocations: 26.263 GiB, 12.67% gc time)


0.9715932350277648

In [60]:
@time M2vdwcalc(configin, [4,4,4], vdwintfourier)

 24.046487 seconds (251.92 M allocations: 26.264 GiB, 12.52% gc time)


0.9715932350277648

In [62]:
@time M2vdwcalc(configin, [4,4,4], vdwintfourier)

 23.251902 seconds (251.92 M allocations: 26.263 GiB, 12.92% gc time)


0.8773272971871421

In [64]:
@time M2vdwcalc(configin, [4,4,4], vdwintfourier)

  7.951508 seconds (50.58 M allocations: 5.263 GiB, 7.60% gc time)


0.8773272971871421

In [65]:
@time M2vdwcalc(configin, [4,4,4], vdwintfourier)

  7.699255 seconds (50.33 M allocations: 5.250 GiB, 7.74% gc time)


0.8773272971871421

In [72]:
@time W3W4vdwcalc(configin,[4,4,4],vdwintfourier)

  5.099386 seconds (205.23 k allocations: 10.135 MiB)


2-element Array{Float64,1}:
  0.00023840404135839444
 -1.0809877295358181e-5

In [81]:
@time M2vdwcalc(configin, [4,4,4], vdwintfourier)

  4.534448 seconds (610.17 k allocations: 50.847 MiB, 0.35% gc time)


1.065859172970889

In [76]:
@time testM2vdwcalc(configin, [4,4,4], vdwintfourier)

102.525531 seconds (1.96 G allocations: 89.262 GiB, 14.72% gc time)


1.0658591729708868 + 2.1026316706164913e-18im

In [84]:
@time M2vdwcalc(configin, [8,8,8], vdwintfourier)

2252.463336 seconds (22.02 M allocations: 2.297 GiB, 0.01% gc time)


1.6484439292361643